language: python
python:
  - 3.5
  - 3.6

install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -e .

script:
  - coverage run --source=pytaskmanager pytaskmanager/utest.py

after_success:
  - coveralls
