language: python
python:
  - 3.5
  - 3.6

install:
  - pip install coverage
  - pip install python-coveralls
  - pip install -e .

script:
  - cd ..
  - coverage run --source=ppdli ppDLI/pytaskmanager/utest.py

after_success:
  - coveralls
