application:
  ip: '0.0.0.0' # ip address to listen on
  port: 5000.   # port to listen on
  api_path: /api
  logging:
    level:        DEBUG                  # Can be on of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL'
    file:         default.log            # Filename of logfile
    use_console:  True                   # Log output to the console?
    backup_count: 5                      # Number of logs to keep
    max_size:     1024                   # Specified in kB (i.e. 1024 means a maximum file size of 1MB)
    format:       "%(asctime)s - %(name)-14s - %(levelname)-8s - %(message)s"
    datefmt:      "%Y-%m-%d %H:%M:%S"

environments:
  test:
    description: Test
    type: test
    uri: sqlite:///test.sqlite
    allow_drop_all: True

  prod:
    description: Production
    type: prod
    uri: sqlite:///prod.sqlite
    allow_drop_all: False

